services:
  postgres:
    image: docker.io/library/postgres
    environment:
      POSTGRES_PASSWORD: saerro321
      POSTGRES_USER: saerrouser
      POSTGRES_DB: data
    network_mode: host
    ports:
      - 5432:5432
